### ISSUE TITLE
Compiling on ArchLinux

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/blueberry#1]
Greetings, I like the work you're doing on this tool so you can bring Bluetooth support on some other OS with gnome-bluetooth >= 3.14.

My question is that if you can give some instructions on how to compile this program on ArchLinux, I was watching this page (http://segfault.linuxmint.com/2013/10/how-to-build-and-install-the-latest-cinnamon-from-git/) but the instructions are for Debian/Ubuntu mainly and I would like to know if there is a generic way to do this. I'm planning on installing Arch at the end of this month (if everything goes ok) and, as you may know, cinnamon-bluetooth no longer works there but I believe that this tool can make a great job

I don't know if this is supposed to be considered an issue but I'll leave it here just in case. Greetings

**Comment by mtwebster** [comment]
The good news for this, is that there really is no compiling to be done, since this is written in python.  It's mainly about getting the files in their proper location -

etc folder gets merged in with your /etc
usr folder in with you /usr

The closest thing to compiling would be to get the po (translation) files in their right spot and compiled - the Makefile actually does this in Mint, but I'm not sure that's a valid spot in Arch.  If you're ok with just English, you can skip this.

If you want to actually *package* this for Arch, you could probably grab an existing package's pkgbuild file and modify it - there are plenty out there that are no-compile/packaging only.

**Comment by SamBurgos** [comment]
Greetings, I uploaded a PKGBUILD sample file with the information that I copied from another package (cinnamon-bluetooth from AUR), I don't know if I got this right (from IRC told me to read the wiki and to get a sample that can do the same to study and modify) but I'll try to get this updated as much as possible, link is down below.

I got pending to install Arch, test dependencies, check if it makes the process to merge the folders you told me and the language part  (almost nothing ;) ). Since I'll be busy in these weeks (mainly because of my studies and final terms) I can't promess to give it a try on the next few days but I'll add it on my to-do list after I'm done (including install Arch).

Link for the temporary PKGBUILD template (search in the folder blueberry). If I got something wrong and you (or someone else) can correct me I'll answer to it. -> https://github.com/SamBurgos/Random-and-Gists

**Comment by SamBurgos** [comment]
Greetings again, I hope you are doing it great with the soon-to-be release of Mint 17.2 as well as the team, as promised I installed Arch (after a little bit of suffering) and I, kind of, manage to "install" blueberry; I said "install" because I actually did the copying/merging in a manual way instead of the PKGBUILD way (still working on it, and really need a lot of help on that one)

Anyway, after a lot of testing for now I manage to get it run and got some good and bad news on that part:

* I manage to pair it with my phone and get it running as well, I tested sending some files and it actually works!!
![selection_002](https://cloud.githubusercontent.com/assets/1509924/7826687/f61284ee-03da-11e5-8d3d-a0810d8b81e1.png)

* I don't know if its the theme, the version of the program (I downloaded 1.0.4 version because it's the latest tar.gz file uploaded here and I have to work with it because of the AUR rules) but I got a missing icon in the program, unfortunately I don't have a spare PC where I can install LMDE so I can see how it should works. I try it with the Mint-x theme (screenshot above) and another theme with the same results (screenshot below)
![selection_001](https://cloud.githubusercontent.com/assets/1509924/7826752/be320378-03db-11e5-8f4e-f7cf8eff8034.png)

* When I run Blueberry from the usual way, I got a little problem that it doesn't show a systray icon as it should, again I'm a little lost with this
![workspace 1_001](https://cloud.githubusercontent.com/assets/1509924/7826776/0e8d53e0-03dc-11e5-92de-8f33eb77f621.png)

* Today I tried to run Blueberry from terminal to get a little bit more info on the problem, I got the message attached on the screenshot. Like I told you I copied manually all of the files required to the respective folders and even if I manage to get it running great I have that issue. Do I forgot something in the copying or maybe permissions that I forgot to grant?
![workspace 1_003](https://cloud.githubusercontent.com/assets/1509924/7826811/7647d6ea-03dc-11e5-929f-a644506a22f0.png)

* From what I got, apparently /usr/share/locale/$LANG/LC_MESSAGES is the location of the translation files on Archlinux too so I guess that the makefile could do great, although I got questions on that part too

I tried to contact you on #linuxmint-dev but apparently you where busy doing something else, or I don't know if in your time zone when I'm awake you're sleeping or viceversa. I don't want to interrupt you on the Mint part and really sorry to annoy you but I would really try to help to put this working so others can benefit from your work. If you need to ask me more things I'll try to answer here or at my mail if you wish. Greetings and good luck with the release of Mint and Cinnamon

**Comment by mtwebster** [comment]
Hmm - did you end up running glib-compile-schemas to make sure the settings stuff was integrated into your system?  The file `org.blueberry.gschema.xml` gets copied to `/usr/share/glib-2.0/schemas`, then you run:

`glib-compile-schemas /usr/share/glib-2.0/schemas`

Also the file 'blueberry-tray' should exist in /usr/bin, and *must be executable*

As far as the icon, I'm not sure - gnome-blueberry is handling that.  Does using the Adwaita/gnome icon theme help?

As for it showing up in cinnamon settings, it will if `blueberry` is in /usr/bin and executable also.

**Comment by SamBurgos** [comment]
Let me review your comments point by point:
* I had some hard time deducing the glib-compile-schemas part, I guess I found it on the AUR GNOME packaging rules but I did run it after I copied the file and the terminal gave me an output of "missing schemas" or something.
* I did copy all the required files as you told me, in the PKGBUILD created on my repo I added the files that I copied in order to have it running so I hope I didn't miss anything (I can't upload the PKGBUILD officially yet since I have some other problems and I need a lot of help, but that's another business).
* About the tray and the icon, let me have a try once I go back home and I'll let you know about it (Arch is on my laptop and I'm at work at the moment of answer this) but as far as I remember, even with the Adwaita icon it didn't showed up.
* About executable permissions I'm not so sure if I missed that part, again, I'll check once I'm home

I'll write you again once I check everything you told me. Thanks for the help

P.D.: Did you mean *"gnome-bluetooth"* instead of *"gnome-blueberry"* in the icon paragraph :stuck_out_tongue_winking_eye: ?

**Comment by mtwebster** [comment]
Yes - gnome-bluetooth - sorry :)

The missing schemas part is weird.. that should just give no output.  Check that folder actually has other gschema.xml files in it.  Maybe it's a different location on Arch (though they're usually about as 'standard' as it gets)

**Comment by SamBurgos** [comment]
Well, after arriving kind of late to my home and giving a try on your recommendations I got the following results:

* I updated again the schemas, I did it last time after copying so I didn't forget that one; no worries, it's standard on any Linux OS 
![workspace 1_004](https://cloud.githubusercontent.com/assets/1509924/7851062/4ff39f80-04a7-11e5-8ff0-d6625cc7c69b.png)

* I don't know if maybe the manual copy made me forget about giving permissions but neither _blueberry_ or _blueberry-tray_ has exec permissions, I changed that (my mistake on that one)
![workspace 1_005](https://cloud.githubusercontent.com/assets/1509924/7851041/17991f8e-04a7-11e5-8c7f-fe91e5963498.png)

* Unfortunately even after giving exec permissions to both binaries, blueberry doesn't appear on the settings
![workspace 1_006](https://cloud.githubusercontent.com/assets/1509924/7851084/9ccadfc6-04a7-11e5-98fa-6e2420cb0c70.png)
Also when I try to run __cinnamon-settings blueberry_ it recognizes the command but nothing happens except the warning messages that I circle
![santiago arch-hp -usr-lib-blueberry_007](https://cloud.githubusercontent.com/assets/1509924/7851097/cdaec71a-04a7-11e5-8e55-c4968c5f199f.png)

* In all of my screenshots, as you can see, I manage to get the icon running but it only shows an empty icon, changing the theme to Adwaita doesn't do anything (first screenshot). Am I missing a dependency that only works on LMDE or should I forgot to install something else? Maybe there's something that I forgot or a library that doesn't work or exist in Arch, you can see my PKGBUILD to see if I'm missing something or a dependency (second and third screenshots), like I told you I'm a freshman doing this kind of things and I know that I kind of sucks, so sorry if I got something wrong
![themes_008](https://cloud.githubusercontent.com/assets/1509924/7851134/5e4a9c22-04a8-11e5-94da-72b9a19fda48.png)

![mozilla firefox_009](https://cloud.githubusercontent.com/assets/1509924/7851200/2c32263c-04a9-11e5-9c18-3471c00b9281.png)

![mozilla firefox_010](https://cloud.githubusercontent.com/assets/1509924/7851207/36255cc2-04a9-11e5-8831-74727d6161cb.png)

I would like to give you a hand somehow so I'm giving my best to study the code and trying to understand it, python is something that I haven't seen yet or tried even though I wish to and C (in case I have to check the whole code on gnome-bluetooth) is kind of dusty. So please if I'm doing something wrong don't hesitate in tell me what is it, also I tried to contact you on IRC with no luck (I started reading the linuxmint.github.io page trying to learn how not to do things wrong). For now that's it and I hope this helps you somehow

**Comment by mtwebster** [comment]
What version of Cinnamon are you on?  If you open /usr/lib/cinnamon-settings/cinnamon-settings.py and search for "blueberry" is it there?  It may be in /usr/share/cinnamon-settings on Arch (just search for that file)

Also, as for IRC - I'm always in there, but not always at the keyboard - if you try to get ahold of me or anyone in -dev, be patient, I'll see it sooner or later - apologies if I missed it.  Don't hesitate to ask questions (whether you think they're dumb or otherwise) - or try things out - this is how you learn.

**Comment by SamBurgos** [comment]
Right now I'm using Cinnamon 2.4.8 according to the output
![workspace 2_013](https://cloud.githubusercontent.com/assets/1509924/7874694/753494ec-0570-11e5-89ae-6d28ef31774b.png)

As for the files you told me, blueberry doesn't appear neither in /usr/share/cinnamon-settings (screenshot above) or in cinnamon-settings.py (screenshot below), should I wait for the 2.6 version to check once again or should I try another thing? I tried adding a line or modifying but apparently I can't manage to make it work or appear in the control center
![workspace 1_012](https://cloud.githubusercontent.com/assets/1509924/7874703/a6f667bc-0570-11e5-9e59-7a11c74edc2e.png)

As for the IRC I'll try to leave the messages but I can't promise to be online all the time, although I have hexchat installed in Arch (my laptop) and Mint (my workplace); I won't be capable to test things until I return to my home and check it once again in here, for now we can keep in touch through here or my email, I assume you are in a different time zone (-06:00 GMT is in my country El Salvador) so I'm not sure if we will be capable to communicate in real time even if both try our best to be in front of the computer :P; if it doesn't matter the situation I'll write it in IRC if you wish. Greetings

**Comment by dalcde** [comment]
How about this: dec41.user.srcf.net/blueberry-1.0.7-1.src.tar.gz

**Comment by SamBurgos** [comment]
@dalcde I'll give it a try once I return home but if you said that I must have Cinnamon 2.6 version then I'll have to wait until the packager/maintainer add that version in the Arch repos so there's nothing I can do about it. About the file you sent I checked the data and I'll try to check it if it works with the dependencies, only a question if I may: Why the .zip file and not the tar.gz?

@mtwebster A little bit offtopic: I found another bug on Blueberry, should I open another issue?

**Comment by dalcde** [comment]
No idea why I picked the .zip file. Maybe because it was the first item on the list?

**Comment by SamBurgos** [comment]
@mtwebster @dalcde Thank you so much for all of your effort, your guidance and your patient with me!! Thanks to the both of you now the package is a reality and the people of ArchLinux is capable to have a functional bluetooth tool in Cinnamon once again. To be honest I don't know what will happen next or how am I going to fix problems if the need arise, also I would like to collaborate to keep improving this somehow _starting to search and read about python and gtk3 desperately_

A couple of screenshots of your tool in action
![workspace 1_014](https://cloud.githubusercontent.com/assets/1509924/7895326/33501b80-0644-11e5-913c-efc2b5c297cd.png)

![workspace 2_015](https://cloud.githubusercontent.com/assets/1509924/7895328/6538fe00-0644-11e5-8056-f515327dbbc9.png)

![workspace 1_016](https://cloud.githubusercontent.com/assets/1509924/7895337/f27848a2-0644-11e5-9c6b-78aba278e52e.png)

I don't know if I should be the one to close this but, in my personal opinion, I can consider this "issue" as solved so if I have to be the one to do it let me know; otherwise I'll let you the honors on this. Thanks again
