### ISSUE TITLE
Python 2 is still required?

### ISSUE THREAD

**Issue by Nicholas-Baron** [linuxmint/blueberry#101]
Python 2 is being [sunset](https://www.python.org/doc/sunset-python-2/). I have tried to remove Python2 from my Mint 19.3 laptop. 
Aptitude says that blueberry 1.3.4 requires python < 3 (a shorthand to say only Python 2). I do not see any file in this repository that explicitly requires Python 2.
1. Is there some dependency that needs Python 2 and so blueberry asks for it just to be sure?
2. Will the Mint 20.1 release include a version of blueberry that does not need Python 2? 
3. Ubuntu 20.04 LTS will not have Python 2 ([source](https://itsfoss.com/ubuntu-20-04-release-features/)). Will this be true of the Mint version build on it?

If I am asking these questions in the wrong forum, please direct me to the correct place to ask them.

**Comment by mtwebster** [comment]
Hi, someone forgot to update the dependencies, we've been python3 for a bit.

https://github.com/linuxmint/blueberry/commit/3554065bf7267fb7bfd9639a354746c881b0cb66

Thanks for pointing it out
