### ISSUE TITLE
Blueberry "Visible as 'Bastien's computer' "

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/blueberry#11]
Hi there, on Blueberry 1.0.9 in Manjaro (Arch derivative), Blueberry claims that my computer is visible as "Bastien's computer". No idea where it got that name from, and furthermore it's wrong, my computer is visible via bluetooth as "T530".

**Comment by clevertoucan** [comment]
I'm on BlueZ in Antergos, and I have the same issue... Except on mine BlueZ doesn't recognize my bluetooth device and it fails

**Comment by chadberg** [comment]
I think this is a permissions issue somewhere. It's happening on my computer, but if I run it under sudo it works as expected.

**Comment by brownsr** [comment]
Visible in the Mint 18 Beta.  Happens intermittently, particularly on the first time opened after reboot, at least that is how it appeared to me.

**Comment by cabellicar123** [comment]
I had the same issue. Unblocking the device with `rfkill` allowed it to work, but trying to turn off bluetooth with blueberry reblocked the device and therefore created the issue again.

**Comment by anandrkris** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1571262 Related bug in Ubuntu

**Comment by dtrunk90** [comment]
I'm affected as well. I've turned off my bluetooth as I am using it rarely. After a reboot sometimes my bluetooth is wrongly enabled again. When open up blueberry (1.1.5-1~xenial0; installed from [here](https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon)) my computer name is "Bastien's computer" and the language is english. After turning off and on again it's correct again (computer name "danny" and language is german).
![bildschirmfoto vom 2016-09-05 18-49-17](https://cloud.githubusercontent.com/assets/636557/18254082/9a05b8d4-739a-11e6-9cb0-a80485c3573a.png)
![bildschirmfoto vom 2016-09-05 18-50-33](https://cloud.githubusercontent.com/assets/636557/18254083/9a0a9d36-739a-11e6-8013-99aa8401ecff.png)

**Comment by WalissonRodrigo** [comment]
I Have same problem i restart and the bluetooth start again normaly

**Comment by clefebvre** [comment]
That's upstream in gnome-bluetooth. Bastien is Bastien Nocera and that indicates a misconfiguration in your bluetooth settings. He used his name as a placeholder.. it's a very bad idea in my opinion, but there's not much we can do about it within the scope of blueberry.

**Comment by clefebvre** [comment]
Correction, we managed to introspect the gnome-bt widget and override this behaviour.

**Comment by geckolinux** [comment]
Nice, thanks a lot Clem!
