### ISSUE TITLE
Cannot disable bluetooth 

### ISSUE THREAD

**Issue by huyhoang8398** [linuxmint/blueberry#114]
![image](https://user-images.githubusercontent.com/25379882/126550651-83e13f23-017d-4906-8ad6-63500216873c.png)

Version         : 1.4.4-1
OS: Archlinux
Kernal: 5.13.4-arch1-1

**Comment by leigh123linux** [comment]
![500px × 355px – Website Images (40)_3](https://user-images.githubusercontent.com/1299302/126579637-7fa900f6-b66e-468a-b47c-81609756a365.png)
