### ISSUE TITLE
how to install blueberry

### ISSUE THREAD

**Issue by tiruk007** [linuxmint/blueberry#137]
when i try this below block I'm facing mint-build: command not found
"""#### Building the package

```
# Use mint-build to build the project for the first time.
# This also fetches and installs the build dependencies:
mint-build""""

**Comment by gabrielcarlossl** [comment]
same here, mint cinammon 21.3

**Comment by DirkHaar** [comment]
mint-build works for me (at least "blank", I don't use it).
mint-build --help should deliver
usage: mint-build [-h] [-i] [-s SUFFIX] [-g GIT_REPOSITORY] [-t] [-d DEB_DIR]

Build project

options:
  -h, --help            show this help message and exit
  -i, --install         Install built packages
  -s SUFFIX, --suffix SUFFIX
                        Version suffix
  -g GIT_REPOSITORY, --git-repository GIT_REPOSITORY
                        Git clone URL, or project name (for Mint projects on Github). Suffix with #tagname, #branchname or
                        %pullrequest to specify a branch, a tag, or a pull request to build from.
  -t, --temporary       Use a temporary directory for building
  -d DEB_DIR, --deb-dir DEB_DIR
                        Folder to copy debs to when building is complete. If this option is omitted, the generated debs will not
                        be copied.

**Comment by DusanJovanovic** [comment]
> when i try this below block I'm facing mint-build: command not found """#### Building the package
> 
> ```
> # Use mint-build to build the project for the first time.
> # This also fetches and installs the build dependencies:
> mint-build""""
> ```

You need to install [mint-dev-tools](https://linuxmint-developer-guide.readthedocs.io/en/latest/setup.html#install-mint-dev-tools) in order to use `mint-build` command.
