### ISSUE TITLE
Support for LMDE6

### ISSUE THREAD

**Issue by frode-h** [linuxmint/blueberry#138]
It would be great if this could work in LMDE, because the current BT tool is not very good.

I tried to use this package in LMDE6, but after building the software I discovered that it depends on gir1.2-gnomebluetooth-1.0, which is not available in LM faye or Debian bookworm, while gir1.2-gnomebluetooth-3.0 is.

**Comment by clefebvre** [comment]
It's not compatible with the new gnome-bluetooth unfortunately.
