### ISSUE TITLE
Usability - Device Properties / Settings to be made easily discoverable

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/blueberry#17]
I feel properties of listed devices should be shown using an icon / visual indication that further configuration / settings are available. Not very apparent that further popup window
![settings](https://cloud.githubusercontent.com/assets/4663298/16658619/9d65edd6-4484-11e6-9768-6fe7eccce7da.png)
 is available

![bluetooth](https://cloud.githubusercontent.com/assets/4663298/16658425/f5e91312-4483-11e6-8659-d238e3d0b2f4.png)

For Eg: Wi-fi Network settings shows clearly with settings icon...
![network settings](https://cloud.githubusercontent.com/assets/4663298/16658509/46660c96-4484-11e6-99d0-24f6eca63a6c.png)

**Comment by clefebvre** [comment]
That's down to gnome-bluetooth's setting widget. We can't control that unfortunately.
