### ISSUE TITLE
Audio BT Speaker - Default to A2DP

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/blueberry#18]
Hi , 

At the moment, switching from HSP - A2DP can be done only using Sound Settings. this should be available from blueberry itself. And A2DP should really be the default option.
https://wiki.debian.org/BluetoothUser/a2dp

Thanks.

**Comment by clefebvre** [comment]
That's down to gnome-bluetooth's setting widget. We can't control that unfortunately.
