### ISSUE TITLE
 My computer's name is not "Bastien's computer" 

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/blueberry#20]
There is something that looks like a hardcoded string for "Bastien's computer" as a hostname as visible in bluetooth. That is not the case, and may confuse users. I think this appears after a crash / some issue in bluetooth service.
![bluetooth](https://cloud.githubusercontent.com/assets/4663298/18171916/40d9a14c-7081-11e6-802f-9624e0261f0e.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/blueberry/issues/11

**Comment by anandrkris** [comment]
Apologies for not searching. I thought I had hit something unique.
