### ISSUE TITLE
Security issue: No way to turn off visibility w/o turning off blue tooth.

### ISSUE THREAD

**Issue by MichaelJCole** [linuxmint/blueberry#23]
Hi, I upgraded mint 17->18.  There was no bluetooth config app, so I installed blueberry (found on a blog).

It says my computer is available for file transfers.  I really really don't want that because of security issues.

How can I become invisible, and unavailable for blue tooth file transfers?

I tried this, but blueberry seems to always make my laptop discoverable:

```
☀  bt-adapter --set Discoverable 0
Discoverable: 1 -> 0
☀  bt-adapter --set Discoverable 0
Discoverable: 0 -> 0
☀  blueberry   && echo "Ok"
Ok
☀  bt-adapter --set Discoverable 0
Discoverable: 1 -> 0
```

**Comment by clefebvre** [comment]
gnome-bluetooth (the central widget in blueberry) comes with OBEX but it doesn't work in Mint. So the situation right now, is that although you are discoverable, you cannot receive files.

The new upcoming version of Blueberry, which will come in Mint 18.2, will introduce its own OBEX support and thus will be able to receive files. Upon receiving a request you will get a notification to accept or reject the file.

You'll also be able to disable OBEX support by typing this in a terminal:

`gsettings set org.blueberry obex-enabled false`
