### ISSUE TITLE
Use Case:  Connect to speaker and turn on sound

### ISSUE THREAD

**Issue by MichaelJCole** [linuxmint/blueberry#24]
I have one use case for blueberry, and it's probably the main use case for almost every other user.

> Connect to a speaker and play sound.

Here's the current steps:

1) run 'bluetooth'
2) see speaker in list
3) open details dialog
4) click on
5) Wait for spinny thing
6) click sound settings
7) click speaker in list
8) Close 3 windows

It would be awesome if anyone could:

1) run bluetooth
2) see speaker in list
3) because it's a speaker there's a "Play sound" button.  Click and it does 4-8

If it's not a speaker, then a "Connect" button would be apropos.

Anyways, thanks!  I use what you made and appreciate it :-)

**Comment by clefebvre** [comment]
That's down to gnome-bluetooth's setting widget. We can't control that unfortunately.
