### ISSUE TITLE
Display device name, type, etc in Tooltip

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/blueberry#26]
Not sure if this belongs here or https://github.com/linuxmint/cinnamon-bluetooth/issues/18

At the moment, panel applet shows 1 device connected when am connected to my JBL Flip Speaker. Can this tool tip be enhanced to include more details? Helps avoid opening the application.

 Network for instance display the wireless connection name which is very useful

**Comment by clefebvre** [comment]
https://github.com/linuxmint/blueberry/commit/3eccc7ff41db32885f70bd6dad88a05c29a87c5e
