### ISSUE TITLE
Please consider making it more evident when pairing is finished

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/blueberry#29]
It seems to me that the following window can easily leave the user wondering whether his/her Bluetooth device can now be used. For the devices spinner is still spinning and aside from the word 'connected' there's no no indication that all is ready to go. Or perhaps I find this unclear only because I've had such a struggle to get things working (which they still aren't, even though 'pairing' does seem to have been established).

![image](https://cloud.githubusercontent.com/assets/9998846/22577323/c400bd84-e9b8-11e6-84b3-6d24ecf15dc5.png)

**Comment by clefebvre** [comment]
That's down to gnome-bluetooth's setting widget. We can't control that unfortunately.
