### ISSUE TITLE
Sending files only works one way

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/blueberry#3]
https://bugs.launchpad.net/linuxmint/+bug/1460125

**Comment by BRKsays** [comment]
Hi Clem, is there any workaround to fix this? I'm using Linux Mint Cinnamon 17.2 64-bit.

**Comment by AlexYeCu** [comment]
True. Tried this at fedora with 2 devices, old nokia phone and android tablet. Result is negative: error recieving data via send UI and failed recieving: 1. 
Interesting:  «Connect» switcher turns on for some seconds when recieving.

**Comment by surenenfiajyan** [comment]
Same problem here. Riddles me this: is it a bug(as it says my laptop is available for file transfers ...  bla bla bla bla... Downloads folder) or simply a missing feature?

**Comment by clefebvre** [comment]
Fixed.
