### ISSUE TITLE
Switch OFF Bluetooth from Bluetooth applet, NOT Saved on Next Reboot !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/blueberry#34]
Hi. I already post this in Redhat bugZilla due to the fact I'm on Fedora 24 Cinnamon edition. Today, just few minutes ago, I received new bluetooth packages update but bug is still without fix. For that I decided to post it here:

Description of problem:
I like to prevent bluetooth from switched ON on reboot from by bluetooth applet (blueman bluetooth manager) but I can not !

Steps to Reproduce:
1. Click on "Turn Bluetooth OFF" from list menu of bluetooth applet (blueman bluetooth manager) see screenshot 1. This will turn OFF bluetooth O.K during current session.
2. reboot PC

Actual results:
After reboot laptop, bluetooth reswitched ON automatically

Expected results:
Bluetooth remain switched OFF (Turn Bluetooth OFF of blueman bluetooth manager from previous boot remain effective on new boot)

Additional info:
Before recent updates for blueman which led to appearance of 2 bluetooth icons in panel), I was able to disable bluetooth from switch ON automatically each time launching or reboot my laptop by the following: system setting, Startup Applications, then disable bluetooth start. At that time doing so will prevent bluetooth will never load automatically at start up BUT I WAS STILL BE ABLE TO SWITCH BLUETOOTH ON AGAIN FROM SYSTEM SETTING. Now this is not possible: I should "Turn bluetooth OFF" from list menu of icon of blueman bluetooth manager then disable blueman bluetooth manager from startup application & this will prevent bluetooth from reswitched ON again on next boot BUT I WILL NEVER BE ABLE TO SWITCH ON BLUETOOTH AGAIN UNLESS BY CLICK ON "QUIT" FROM WITHIN ICON OF BLUETOOTH WHICH IS ALREADY SWITCHED OFF THEN ENABLE BLUEMAN ON STARTUP THEN REBOOT LAPTOP AGAIN !!!!

This is regression. Please fix this kindly.
![1](https://cloud.githubusercontent.com/assets/25375330/25851350/ebe6478c-34b4-11e7-8879-c6cd1831d312.png)

Link to this bug on BugZilla is:
https://bugzilla.redhat.com/show_bug.cgi?id=1429473

**Comment by leigh123linux** [comment]
Remove blueman as it isn't part of fedora cinnamon anymore, it was recently switched to blueberry

```
sudo dnf erase blueman
```

**Comment by Nokia808** [comment]
Hi. I did what you command me to do but not work at all !!

I remove blueman as following:

sudo dnf remove blueman

it remove blueman & obexd as a dependency.

Now bluetooth function is completely blocked & I can not power it ON at all !!

I restart my laptop 4 times without result !! Bluetooth perminantly powered OFF !! 

I can not power bluetooth ON from system setting !! When I go to system setting, then underhardware clicking bluetooth, no thing happened !!

Icon of bluetooth (Applet) in Cinnamon panel always gray (inactive) !! Left click over it show nothing !! Right click on it show 2 options "Open bluetooth device manager" & Quit !! Clicking over "Open bluetooth device manager" lead to no thing !! Clicking over Quit will quit icon BUT IT CAN NOT RESTORED AGAIN !!

I thing you do something wrong !! Please I'm on Cinnamon edition of Fedora 24. Cinnamon version is 3.2.8 NOT 3.4 !! I thing you spook about Cinnamon 3.4 which still not reaching Fedora 24 repositories !!

Please your kind help !!
