### ISSUE TITLE
Double bluetooth icons

### ISSUE THREAD

**Issue by martywd** [linuxmint/blueberry#38]
LM 18.2 MATE beta

Issue _after_ logging into LM 18.2 with Bluetooth _disabled_ which happens _every_time_ on my laptop if I forget to do the keypress [Fn+F12] after a reboot and _before_ logging in.  See further details below...

Full description at the beta page (paragraph four):
http://blog.linuxmint.com/?p=3266#comment-135925

and slight elaboration... with reply from 'Clem' which I did not notice until today! (Jun 26)
http://blog.linuxmint.com/?p=3266#comment-135926

Image of double icons here:
https://postimg.org/image/p2864lw5x/
.

**Comment by surenenfiajyan** [comment]
This happens to me too when I disable and then enable the tray icon.

**Comment by rathann** [comment]
I'm also seeing double icons on Fedora with MATE 1.18.0 and bluberry-1.1.15 (https://bugzilla.redhat.com/show_bug.cgi?id=1478751).

**Comment by rathann** [comment]
It looks like this is fixed in 1.1.18 (by commit c54c333d1921d1ff8989c751a8ef7324e02db033).

**Comment by martywd** [comment]
@rathann : Thanks for the update.  Linux Mint pushed a bunch of MATE 1.18.x updates this last weekend but an update for blueberry-1.1.15 (as of today) was not one of them.  Time will tell?
.
