### ISSUE TITLE
spawns two instances of rfkill event

### ISSUE THREAD

**Issue by rathann** [linuxmint/blueberry#50]
Originally [reported in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1533646).

Version-Release number of selected component (if applicable):
```
blueberry-1.1.20-1.fc27.noarch
rfkill-0.5-10.fc27.x86_64
```

How reproducible:
Always.

Steps to Reproduce:
1. open Bluetooth Device Manager
2. toggle "Show a tray icon" switch off and on
3. `ps axf`

Actual results:
```
 7165 ?        S      0:00 /usr/bin/python3 /usr/bin/blueberry
 7166 ?        Sl     0:00  \_ /usr/bin/python2 /usr/lib/blueberry/blueberry.py
 7174 ?        S      0:00      \_ python2 /usr/lib/blueberry/safechild /usr/sbin/rfkill event
 7175 ?        S      0:00      |   \_ /usr/sbin/rfkill event
 7224 ?        S      0:00      \_ /usr/bin/python3 /usr/bin/blueberry-tray
 7226 ?        Sl     0:00          \_ /usr/bin/python2 /usr/lib/blueberry/blueberry-tray.py
 7236 ?        S      0:00              \_ python2 /usr/lib/blueberry/safechild /usr/sbin/rfkill event
 7237 ?        S      0:00                  \_ /usr/sbin/rfkill event
```

Expected results:
Only one instance of rfkill event should be running.

**Comment by mtwebster** [comment]
Both "blueberry" and "blueberry-tray" spawn an `rfkill event` process.  The gui does it to ensure the switch stays synced to the state, and the tray process uses it to sync the icon.

When you close blueberry settings there should only be one corresponding to the tray.

**Comment by rathann** [comment]
You're right. Sorry for the false alarm.
