### ISSUE TITLE
Automatically switch sound output to connected device

### ISSUE THREAD

**Issue by valericus** [linuxmint/blueberry#59]
I use Bluetooth headphones and have to change sound parameters manually each time I connect then (sometimes several times an hour). It would be great feature to make some white list of trusted A2DP devices to enable them as main output source at the moment of connection. User experience should be equal to wired headphones: you plug them to socket and start listening.

**Comment by valericus** [comment]
I'll try to investigate this in my spare time and propose some PR. But no estimates unfortunately.

**Comment by mirh** [comment]
Shouldn't it be up to pulseaudio to remember your device order preference?

**Comment by valericus** [comment]
@mirh yep, you are right. I've discovered `module-switch-on-connect` for pulseaudio, and it's solve my problem in best possible way. Thanks a lot for your advice!

**Comment by mirh** [comment]
Best possible way would be, as I said, the thing remembering how every device "prevails" to each other, IMO.. 
Anyway gg.
