### ISSUE TITLE
Search entails it's doing something, even when bluetooth service is stopped altogether

### ISSUE THREAD

**Issue by mirh** [linuxmint/blueberry#63]
I dunno, give an error and tell the user at least?
Or offer to enable it by calling systemctl or whatnot. 

If it hadn't be for bluetoothctl, I'd still be here wondering why blueberry was taking so long.

**Comment by leigh123linux** [comment]
incomprehensible

**Comment by mirh** [comment]
... Then ask me to clarify?
I'm saying that I hadn't bluetooth service turned on (so \*of course\* nothing could be done). 
YET blueberry was giving me the "spinning circle" thing, as if it was doing something.
