### ISSUE TITLE
Unable to receive files #2

### ISSUE THREAD

**Issue by FrogMcRibbit** [linuxmint/blueberry#76]
I can send files from my laptop to my smartphone, but I can't send files from my smartphone to my laptop. I am using Manjaro Cinnamon.

On my smartphone, I get the following error message: "he Transfer is Forbidden by the target device", even if the "Receive files from remote devices" option in Blueberry is clearly enabled. 

On my laptop, there is no visible symptom at first glance. However, if I do a `systemctl status bluetooth.service`, I see this error when a file transfer from my smartphone to my laptop fails: `bluetoothd[502]: Unable to get io data for Object Push: getpeername: Transport endpoint is not connected (107)`.

Am I missing something? Is there something misconfigured on my distro?

My workaround is simply to uninstall Blueberry and install Blueman instead, unfortunately. With Blueman, I can transfer files from smartphone to laptop without issue once I accepted to receive files from trusted devices. :slightly_frowning_face: 

I see that there is a similar issue here, but I do not have the same kind of symptom though. That's why I decided to create a new issue despite having a similar problem.
https://github.com/linuxmint/blueberry/issues/65

Laptop
Model: Lenovo Ideapad 310
OS: Manjaro (Testing branch)
DE: Cinnamon 4.0.9 (package: cinnamon 4.0.9-1.3)
Kernel: Linux 4.19.26 (package: linux 4.19.26-1)
Bluetooth-related packages: 
- blueberry: 1.2.5-1
- bluez: 5.50-6

Smartphone
Model: LG G7 ThinQ
OS: Android 8.0.0 (Security patch level: Feb 1 2019)

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/blueberry/issues/65
