### ISSUE TITLE
Mouse pairing not working with kernel 5.0.0-15

### ISSUE THREAD

**Issue by viboux** [linuxmint/blueberry#79]
Bluetooth mouse pairing is working fine with kernel 4.15 but stops working with kernel 5.0+. I tried a few weeks ago with a mainline kernel and now I can reproduce with the newly published kernel in Mint today.

I am able to see the mouse in the Bluetooth applet and complete the pairing process. However it shows as Disconnected once the pairing is completed. Turning the BT on/off on the mouse or the computer makes no difference.

Headset pairing works fine. Does not work with the two mouses I tried (Logitech MX Master and Microsoft Designer Mouse).

Laptop: Ideapad 730s
Network:   Device-1: Intel Wireless-AC 9260 driver
Desktop: Cinnamon 4.0.10 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa 
base: Ubuntu 18.04 bionic

Can you tell me what logs or info might be helpful to help diagnose the issue?

**Comment by leigh123linux** [comment]
You will need to report it against the ubuntu kernel.
