### ISSUE TITLE
Add appindicator support

### ISSUE THREAD

**Issue by Mau-G** [linuxmint/blueberry#84]
Would it be possible to implement appindicator support for the tray icon?

Here below is a very basic code for it for testing/preview.

```
#!/usr/bin/python
import os
from gi.repository import Gtk as gtk, AppIndicator3 as appindicator

def main():
  indicator = appindicator.Indicator.new("blueberryindicator", "bluetooth", appindicator.IndicatorCategory.APPLICATION_STATUS)
  indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
  indicator.set_menu(menu())
  gtk.main()

def menu():
  menu = gtk.Menu()
  
  command_one = gtk.MenuItem('Open Bluetooth')
  command_one.connect('activate', blueberry)
  menu.append(command_one)

  exittray = gtk.MenuItem('Quit')
  exittray.connect('activate', quit)
  menu.append(exittray)
  
  menu.show_all()
  return menu
  
def blueberry(_):
  os.system("blueberry")

def quit(_):
  gtk.main_quit()

if __name__ == "__main__":
  main()
  
```

**Comment by shanmukhateja** [comment]
Hi, are you referring to a systray icon and some menus for frequently used features? Issue #72 talks about adding a system tray icon as well as some menus to connect and disconnect devices.

And PR #69 was merged recently with the said features.

You can enable the systray icon on Settings tab.

Or am I missing something?

**Comment by Mau-G** [comment]
@shanmukhateja thank you for your reply. I am referring to appindicator support which offers a "more modern" sytsem tray. It was originally developed by Ubuntu for the Unity desktop but is now also being used as option by Xfce (with its status-notifier panel plugin) and Mate. 

https://ayatanaindicators.github.io/about/

Although Canonical still maintain for appindicators for now, with their focus on Gnome, appindicators found a new home with the ayatana project.

**Comment by Mau-G** [comment]
I was explained about xapp status icon so I'm closing this
