### ISSUE TITLE
Icon check missing

### ISSUE THREAD

**Issue by Dmitry-Borodin** [linuxmint/blueberry#86]
v1.2.5 
If blueberry is closed, icon is removed from tray. When I run blueberry again - icon is still missing.
Have to go to settings and toggle show tray icon off and on again, to see the icon.

**Comment by shanmukhateja** [comment]
Hi, could you provide some info regarding your OS? Also, it would be helpful if you could check if v1.2.9 from Releases tab fixes the said issue?

**Comment by Dmitry-Borodin** [comment]
Mint 19.2 Cinnamon 4.2.4 (up to date version)
With 1.2.9 it's still the case, if i'll close bluetooth app and do menu-bluetooth - window is opening, but I have to go settings->icon off and on to see the icon again.

**Comment by shanmukhateja** [comment]
@Dmitry-Borodin please close this issue.

**Comment by Dmitry-Borodin** [comment]
Thank you, hope to see fixed version soon
