### ISSUE TITLE
Exception when rfkill fails due to /dev/rfkill missing

### ISSUE THREAD

**Issue by rathann** [linuxmint/blueberry#88]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1747466 .

blueberry version: `blueberry-1.2.9`

```
subprocess.py:487:run:subprocess.CalledProcessError: Command '['/usr/sbin/rfkill', 'list', 'bluetooth']' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry-tray.py", line 32, in do_startup
    self.rfkill = rfkillMagic.Interface(self.update_icon_callback, debug)
  File "/usr/lib/blueberry/rfkillMagic.py", line 29, in __init__
    self.have_adapter = self.adapter_check()
  File "/usr/lib/blueberry/rfkillMagic.py", line 35, in adapter_check
    res = subprocess.check_output(RFKILL_CHK).decode('utf-8')
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/sbin/rfkill', 'list', 'bluetooth']' returned non-zero exit status 1.

Local variables in innermost frame:
input: None
capture_output: False
timeout: None
check: True
popenargs: (['/usr/sbin/rfkill', 'list', 'bluetooth'],)
kwargs: {'stdout': -1}
process: <subprocess.Popen object at 0xffff97d56710>
stdout: b''
stderr: None
retcode: 1
```

I asked the reporter to run `rfkill list bluetooth`:
```
rfkill: cannot open /dev/rfkill: No such file or directory
rfkill: cannot read /dev/rfkill: Bad file descriptor
```

**Comment by shanmukhateja** [comment]
Could you paste the output for the following command?

`sudo rfkill list bluetooth`

**Comment by leigh123linux** [comment]
> Could you paste the output for the following command?
> 
> `sudo rfkill list bluetooth`

The info was provided in the bugzilla link

https://bugzilla.redhat.com/show_bug.cgi?id=1747466#c8

```
    rfkill: cannot open /dev/rfkill: No such file or directory
    rfkill: cannot read /dev/rfkill: Bad file descriptor
```

**Comment by shanmukhateja** [comment]
According to the upstream bug, you are expecting to see your wireless network interface inside a virtual machine. That won't work. 
The reason being that the virtualization software just fakes a network interface which typically looks like an ethernet adapter to the guest.

As far as rfkill is concerned - you might have to install the package that contains this command. Again, in a virtual machine that won't do anything useful in the default setup.

**Comment by vladimir-didenko** [comment]
@shanmukhateja I am not sure if it is right place to ask but I don't want to create another issue. Right now if "rfkill list bluetooth" command fails it throws an exception that is visible in terminal. But when you start blueberry from GUI there is no indication for user what went wrong. Is this considered as expected behaviour?

**Comment by shanmukhateja** [comment]
@vladimir-didenko  I'm no expert but, from what I understand from the source code, the software doesn't actively report errors to GUI. 

An exception to this would be #83 which reports back permission denied issues for turning bluetooth on/off.

I would highly recommend creating another issue as your query isn't related to this issue. This would help us locate and navigate issues much better.
