### ISSUE TITLE
bluetooth unable to search device 

### ISSUE THREAD

**Issue by mohdzain98** [linuxmint/blueberry#95]
**** In crash reports it is saying /usr/bin/bt-adapter
![crash](https://user-images.githubusercontent.com/55584600/71304110-0a468500-23e8-11ea-9cc8-a7f2a7a1e5c3.png)

**** In System Logs it is saying Process 19196 (bt-adapter) of user 1000 dumped core and 
**** Bluetooth: hci0: RTL: download fw command failed (-110)

 ### Here is a pastebin
===================================================================
 Info                                                              
===================================================================
           PID: 19196 (bt-adapter)
           UID: 1000 (zain)
           GID: 1000 (zain)
        Signal: 6 (ABRT)
     Timestamp: Sat 2019-12-21 11:23:28 IST (20min ago)
  Command Line: bt-adapter -i
    Executable: /usr/bin/bt-adapter
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (zain)
       Boot ID: 24101185f2ac46eb823714ce648fd15b
    Machine ID: f3d85c83fd6e458aba76dbf56f683032
      Hostname: GEEK
       Storage: /var/lib/systemd/coredump/core.bt-adapter.1000.24101185f2ac46eb823714ce648fd15b.19196.1576907608000000.lz4
       Message: Process 19196 (bt-adapter) of user 1000 dumped core.
                
                Stack trace of thread 19196:
                #0  0x00007f96a236fe97 __GI_raise (libc.so.6)
                #1  0x00007f96a2371801 __GI_abort (libc.so.6)
                #2  0x00007f96a2d88335 g_assertion_message (libglib-2.0.so.0)
                #3  0x00007f96a2d8839a g_assertion_message_expr (libglib-2.0.so.0)
                #4  0x000055722dfaeeeb n/a (bt-adapter)
                #5  0x000055722dfaa719 n/a (bt-adapter)
                #6  0x00007f96a2352b97 __libc_start_main (libc.so.6)
                #7  0x000055722dfaad5a n/a (bt-adapter)
                
                Stack trace of thread 19198:
                #0  0x00007f96a2445bf9 __GI___poll (libc.so.6)
                #1  0x00007f96a2d615c9 n/a (libglib-2.0.so.0)
                #2  0x00007f96a2d61962 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f96a2a450e6 n/a (libgio-2.0.so.0)
                #4  0x00007f96a2d89195 n/a (libglib-2.0.so.0)
                #5  0x00007f96a1ea76db start_thread (libpthread.so.0)
                #6  0x00007f96a245288f __clone (libc.so.6)
                
                Stack trace of thread 19197:
                #0  0x00007f96a2445bf9 __GI___poll (libc.so.6)
                #1  0x00007f96a2d615c9 n/a (libglib-2.0.so.0)
                #2  0x00007f96a2d616dc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f96a2d61721 n/a (libglib-2.0.so.0)
                #4  0x00007f96a2d89195 n/a (libglib-2.0.so.0)
                #5  0x00007f96a1ea76db start_thread (libpthread.so.0)
                #6  0x00007f96a245288f __clone (libc.so.6)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 19196]
[New LWP 19198]
[New LWP 19197]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `bt-adapter -i'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f96a3227880 (LWP 19196))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 19196]
[New LWP 19198]
[New LWP 19197]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `bt-adapter -i'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f96a3227880 (LWP 19196))]
#0  0x00007f96a236fe97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f96a2371801 in __GI_abort () at abort.c:79
#2  0x00007f96a2d88335 in g_assertion_message () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f96a2d8839a in g_assertion_message_expr () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000055722dfaeeeb in  ()
#5  0x000055722dfaa719 in  ()
#6  0x00007f96a2352b97 in __libc_start_main (main=0x55722dfaa160, argc=2, argv=0x7ffee8c049b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffee8c049a8) at ../csu/libc-start.c:310
#7  0x000055722dfaad5a in  ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 19196]
[New LWP 19198]
[New LWP 19197]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `bt-adapter -i'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f96a3227880 (LWP 19196))]

Thread 3 (Thread 0x7f96a06a1700 (LWP 19197)):
#0  0x00007f96a2445bf9 in __GI___poll (fds=0x55723006ffc0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007f96a2d615c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f96a2d616dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f96a2d61721 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f96a2d89195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f96a1ea76db in start_thread (arg=0x7f96a06a1700) at pthread_create.c:463
        pd = 0x7f96a06a1700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140284913129216, 2525043775851837919, 140284913127040, 0, 93948920393728, 140732803335488, -2582953768480556577, -2582952669334095393}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f96a245288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f969fea0700 (LWP 19198)):
#0  0x00007f96a2445bf9 in __GI___poll (fds=0x557230086e80, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007f96a2d615c9 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f96a2d61962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f96a2a450e6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f96a2d89195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f96a1ea76db in start_thread (arg=0x7f969fea0700) at pthread_create.c:463
        pd = 0x7f969fea0700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140284904736512, 2525043775851837919, 140284904734336, 0, 93948920393888, 140732803335872, -2582816325768988193, -2582952669334095393}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f96a245288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f96a3227880 (LWP 19196)):
#0  0x00007f96a236fe97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 93948886147440, 93948886164980, 140284954058847, 93948920513524, 24, 2064, 124, 93948886146400, 140732803336144, 140284947188800, 140284943685592, 570840580096, 2048, 347502280704, 7}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f96a2371801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xa2db3ff9, sa_sigaction = 0xa2db3ff9}, sa_mask = {__val = {140284637784976, 0, 140732803336144, 140728898420737, 17019670342908119552, 72057594037927936, 16777216, 6917529027641081856, 93950127898624, 140284637784976, 0, 0, 17019670342908119552, 93948886146400, 140284637784976, 97}}, sa_flags = -1560105504, sa_restorer = 0x7ffee8c047d0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f96a2d88335 in g_assertion_message () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f96a2d8839a in g_assertion_message_expr () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000055722dfaeeeb in  ()
#5  0x000055722dfaa719 in  ()
#6  0x00007f96a2352b97 in __libc_start_main (main=0x55722dfaa160, argc=2, argv=0x7ffee8c049b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffee8c049a8) at ../csu/libc-start.c:310
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -8507693218698774049, 93948886035760, 140732803336624, 0, 0, -2524530997119829537, -2582949051717928481}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7f96a303c733 <_dl_init+259>, 0x7f96a2d0b5b8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -1560033485}}}
        not_first_call = <optimized out>
#7  0x000055722dfaad5a in  ()
#0  0x00007f96a236fe97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f96a2371801 in __GI_abort () at abort.c:79
#2  0x00007f96a2d88335 in g_assertion_message () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f96a2d8839a in g_assertion_message_expr () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000055722dfaeeeb in  ()
#5  0x000055722dfaa719 in  ()
#6  0x00007f96a2352b97 in __libc_start_main (main=0x55722dfaa160, argc=2, argv=0x7ffee8c049b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffee8c049a8) at ../csu/libc-start.c:310
#7  0x000055722dfaad5a in  ()

**Comment by leigh123linux** [comment]
bt-adapter is part of bluez-tools, I see nothing in the backtrace to indicate that blueberry is to blame.
Please file the issue against bluez-tools at Launchpad bug tracker.
