### ISSUE TITLE
ModuleNotFound: gi

### ISSUE THREAD

**Issue by Niwla23** [linuxmint/blueberry#96]
Hi, I am getting a module not found error for gi.
I tried doing apt install python3-gi, but it said its already installed.
The error appears directly when starting blueberry
What can I do?

**Comment by leigh123linux** [comment]
Have you installed a non system provided python version?

**Comment by Niwla23** [comment]
no, not that i know

**Comment by leigh123linux** [comment]
Can you post
```
python3
import gi
```

**Comment by Niwla23** [comment]
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'

**Comment by leigh123linux** [comment]
@Niwla23  Your python3 instalation is busted, post
```
alternatives --list |grep python
```

**Comment by Niwla23** [comment]
@leigh123linux Command does not exist.
Do you mean galternatives?

**Comment by mtwebster** [comment]
What distro is this?

What does `which python3` return?

then, `ls -la  /usr/bin/python3*`

and, lastly `ls -laR /usr/local`

**Comment by Niwla23** [comment]
which python3
`/usr/local/bin/python3`

ls -la /usr/bin/python3*
```
lrwxrwxrwx 1 root root       9 Okt 25  2018 /usr/bin/python3 -> python3.6
-rwxr-xr-x 2 root root 4526456 Nov  7 11:44 /usr/bin/python3.6
lrwxrwxrwx 1 root root      33 Nov  7 11:44 /usr/bin/python3.6-config -> x86_64-linux-gnu-python3.6-config
-rwxr-xr-x 2 root root 4526456 Nov  7 11:44 /usr/bin/python3.6m
lrwxrwxrwx 1 root root      34 Nov  7 11:44 /usr/bin/python3.6m-config -> x86_64-linux-gnu-python3.6m-config
lrwxrwxrwx 1 root root      16 Okt 25  2018 /usr/bin/python3-config -> python3.6-config
lrwxrwxrwx 1 root root      10 Okt 25  2018 /usr/bin/python3m -> python3.6m
lrwxrwxrwx 1 root root      17 Okt 25  2018 /usr/bin/python3m-config -> python3.6m-config
```

 ls -laR /usr/local
You dont want to see output, its over 300 lines of output


I am using Linux Mint 19.3

**Comment by leigh123linux** [comment]
Removing /usr/local/bin/python3 will fix the issue

**Comment by mtwebster** [comment]
I did want to see, there should be very little in there (you could use something like [dpaste](dpaste.com)).  But if what @leigh123linux suggests fixes things, I suppose it's ok.

If you discover any other broken things in your system, that's the first place i'd look :)

**Comment by Niwla23** [comment]
> Removing /usr/local/bin/python3 will fix the issue

Wont that delete python?

**Comment by leigh123linux** [comment]
> > Removing /usr/local/bin/python3 will fix the issue
> 
> Wont that delete python?

Only the local copy, system should take over once it's deleted, env prefers local so override system python.
I suspect some third-party app installed the locale python copy.

**Comment by Niwla23** [comment]
Yay, thank you, working now
